### ISSUE TITLE
Add NFT-minting capability to the SDK

### ISSUE THREAD

**Issue by victorges** [livepeer/ui-kit#10]

**Comment by 0xcadams** [comment]
What does this functionality look like? I think this should be moved to Discussions to decide how we'd implement this, and if this is necessary in an SDK

**Comment by victorges** [comment]
@0xcadams This is what we have today on the separate `video-nft` SDK, and we want to have a similar functionality on the `livepeer.js` SDK: https://www.npmjs.com/package/@livepeer/video-nft

It basically uses the Studio NFT metadata capability, also stored on IPFS, and then integrates with user wallets through web3 libs to simplify the minting process as well. The idea is to make it extremely simple for developers to get started on an NFT minting app, ideally without needing to bring their own IPFS (or other dStorage provider) for it. The current NFT SDK also brings a default ERC20 contract that can be used for the minting for quicker getting started (currently on Polygon, could be easily deployed on Ethereum as well).

Both the NFT metadata and the wallet/contract integrations could be rethought anyway to be made more generic/ergonomic for the developer. We also want to add support for other chains, not only EVM-compatible. @pglowacky can bring more context on the product requirements like the NFT capability itself and the integration with other chains.

I think it's also a possibility that we could keep this functionality, at least the actual-minting bits, out of the core/react packages of the SDK, or at least out of the `LivepeerProvider` interface. Could be a composition on top of it that receives a provider and has the other helpers, as those can be functionalities independent of the provider implementation (tho the provider might need to support at least the NFT metadata dstoring? not necessarily tho). It could be a separate package inside the repo for example, imported like `livepeer.js/nft` or sth like that.

**Comment by 0xcadams** [comment]
Do we have feedback from users on our first iteration of the `video-nft` SDK? I think it would be hard to make a generic-enough interface for minting NFTs that could fit into livepeer.js. The metadata and smart contract functionality is highly use-case specific and it would be hard to generalize those into a one-size-fits-all approach.

For example, every ERC-721 contract has a different approach to how the NFTs are actually minted. The ERC-721 contract (and the NFT minter itself) assumes an ABI of `mint(address owner, string memory tokenURI)`, which is fairly simple compared to how a lot of mature NFT contracts behave in the wild. I think it will be very hard to capture each use-case in our SDK.

We also already handle the upload and export to IPFS functionality from that SDK, so it would just be the contract interaction piece, which IMHO should be left to the user. Maybe we could provide some helpers with exporting the metadata to IPFS (some kind of hook(s) to interact with IPFS?), I just don't see an easy way to capture the minting process in this SDK.

**Comment by victorges** [comment]
Right! I meant ERC721 yeah sorry, doing a thousand things at once 🥲

On the high level I agree we need some user research before creating a V1 of the NFT minting to put in our official SDK. As I've shared with Paige, the current one was almost a hack I made before ETH Denver and does not address any user research. We've only seen it used in hackathons (and hackers seemed to really like it), but I'd say it'd be hard to use it in a production application for the same reasons you mentioned.

As for the minting interface, that is definitely an MVP. The better interface I imagined would provide developers with some "mint" lambda which receives the contract instance and IPFS CID and they can call their contract however they want. Still keeping that default minting function on the default contract anyway, for a really quick getting started (e.g. hackathons).

As for exporting to IPFS, the SDK supports storing the asset to IPFS, but to mint an NFT you need to also create the NFT metadata on decentralized storage, ideally following one of those common standards. I don't think it is a good dev XP to require devs to also bring their own IPFS provider, only for the metadata. As part of that hack I did, the Studio API also supports doing that, but the interface evolved a little weird, which is why I didn't think it was worth including in the generic `LivepeerProvider` interface right now. So that's the bit we'd need to rethink to include in the SDK as well to support minting (independent of the contract interaction).

**Comment by pglowacky** [comment]
Thanks @0xcadams and @victorges for your thoughts on this. We've long suspected that the Minting SDK doesn't address any clear use cases and perhaps this is a good opportunity to write fresh requirements for a minting feature that does address a specific use case. I think it might be worthwhile to put together some research questions and I'll send those to both of you to take a look at. 

cc @ericxtang

**Comment by 0xcadams** [comment]
> As for exporting to IPFS, the SDK supports storing the asset to IPFS, but to mint an NFT you need to also create the NFT metadata on decentralized storage, ideally following one of those common standards.

That makes sense! It might be worthwhile to research more into how we want to handle metadata in the future (Studio currently can handle metadata, but how does that get replicated to IPFS, does the CID change if the metadata updates, etc). I really like the idea of having video metadata stored in IPFS and giving users an easy way to manage that. And encouraging defaults that conform to the ERC-721 spec.

As far as the minting step is concerned, if we already cover the hackathon use-case with the `video-nft` SDK, I'd imagine that other libraries like ethers or wagmi could handle the contract interaction piece much better than we can. Users would already need to have a library for wallet connection/interaction, so giving them the responsibility of actually performing the contract interaction (given a IPFS/Arweave/dStorage CID) doesn't seem like a huge ask. We could always outline that final step in an example in the docs.

**Comment by adamsoffer** [comment]
I agree with Chase's line of thinking here that Livepeer and this sdk's role should be setting the developer up for success prior to minting (using cached media for playback, tooling around metadata etc). It shouldn't necessarily bear responsibility for that last mile where minting functionality gets invoked, rather developers should use libraries for that last mile of contract interaction such as ethers.js or any other chain library, and we can assist developers with this last step via the docs.

**Comment by 0xcadams** [comment]
Closing in favor of https://github.com/livepeer/livepeer.js/issues/55
