### ISSUE TITLE
Add support for Arweave autoupload in Player

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#116]
We currently support autoupload for IPFS CIDs - the backend supports Arweave and this should be added to the SDK

https://livepeerjs.org/react/Player#autourlupload

**Comment by hthillman** [comment]
Can we also make sure that this is specified in the docs for useCreateAsset?

**Comment by pglowacky** [comment]
This ticket should include documentation of the functionality and mimic the  Play a Video from IPFS page.

**Comment by 0xcadams** [comment]
Fixed in https://github.com/livepeer/livepeer.js/pull/129
