### ISSUE TITLE
[bug] Show a more informative error in player if asset upload/processing in Studio failed

### ISSUE THREAD

**Issue by yondonfu** [livepeer/ui-kit#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

If asset upload/processing in Studio fails in https://livepeerjs.org/examples/react/ipfs-playback there is no indication of an explicit failure with an error message and there just seems to be an endless spinner.

### Expected Behavior

An indication of explicit failure with an error message would be helpful to tell the user that something failed as opposed to an endless spinner.

Maybe there is some generic error message shown by the player showing that a failure happened.

### Steps To Reproduce

Try ipfs://bafybeib7uwkq6rfy545yugvrep46kdgjnxvo3432gy6qx5y2dghy2n75u4 at https://livepeerjs.org/examples/react/ipfs-playback

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://livepeerjs.org/examples/react/ipfs-playback

**Comment by 0xcadams** [comment]
Fixed in https://github.com/livepeer/livepeer.js/pull/129

**Comment by 0xcadams** [comment]
<img width="839" alt="Screenshot 2022-11-02 at 11 22 19 AM" src="https://user-images.githubusercontent.com/32714304/199571162-81a19e06-b677-4be7-8c9e-40c98d10dac4.png">
