### ISSUE TITLE
Identify which libraries to use

### ISSUE THREAD

**Issue by victorges** [livepeer/ui-kit#151]
RTMP or SRT or WebRTC or etc

**Comment by clacladev** [comment]
On iOS it works properly. The broadcast stream is received and playback correctly.
Thulinma approved it with reserve https://discord.com/channels/423160867534929930/1039176702158458922/1044383043529486466

On Android it does not work with Livepeer. The RTMP content reported has corrupted timestamps.
I reported a bug here
https://github.com/apivideo/api.video-reactnative-live-stream/issues/46
and here
https://github.com/ThibaultBee/StreamPack/issues/58
