### ISSUE TITLE
.m3u8 is slow to load in the Livepeer player

### ISSUE THREAD

**Issue by pglowacky** [livepeer/ui-kit#166]
Sometimes during live streams, the player is slow to load the .m3u8

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/25b8c06e-5bcf-4590-83a8-a35c299684dc)

**Comment by pglowacky** [comment]
Determined to be a backend bug -- potentially a multinode replication issue

**Comment by 0xcadams** [comment]
Closing since not a livepeer.js issue
