### ISSUE TITLE
Player should error when content is token gated or inactive 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/ui-kit#167]
Currently, when the player is using an HLS URL that contains either content that has not begun yet or the user is not using a signed URL for token-gated content, the player will display an infinite spinner. This gives the impression that the content will begin shortly; when it doesn't, the user assumes that something has gone wrong. 

An ideal solution looks like:
- When a stream has not started yet or is inactive, the player does not display the spinner -- just an empty player. 
- When a stream has started, but it isn't displayed yet or is pending, the spinner is shown. 
- If the viewer is not using a signed URL when a stream has a playback policy of `signed`, "It looks like you don't have permission to view this content" 
- [ADDED 12/12/22]: Report via telemetry when errors occur

_EDITED by @0xcadams_:
- IPFS auto playback while an asset is waiting to be uploaded to studio and the transcoded version played back - see [discord chat here](https://discord.com/channels/423160867534929930/1042472815586197554/1046893233424302141)

Future iterations might include:
- Allowing users to configure their own error messages

**Comment by 0xcadams** [comment]
The problem is, we can't distinguish between "started" and "inactive" from the Player with only the `playbackId`. Unless we add additional info to the `playback info` endpoint, we will not be able to implement this cc @victorges

**Comment by 0xcadams** [comment]
Related, here is the approach api.video takes

<img width="485" alt="Screenshot 2022-11-30 at 3 56 42 PM" src="https://user-images.githubusercontent.com/32714304/204925978-c00a8e27-9189-4b65-a79a-2965e1b2241a.png">

**Comment by 0xcadams** [comment]
I think I was wrong on this, feedback from Victor let me know that this info is returned from the playback info endpoint here:
https://github.com/livepeer/livepeer-com/blob/919536ffd76df4b6f81d8040e65e934284cbef28/packages/api/src/controllers/playback.ts#L16

**Comment by pglowacky** [comment]
@0xcadams Added a note above -- we should report via telemetry when users receive errors and what kind of errors they get.

**Comment by pglowacky** [comment]
@0xcadams Thinking about this more...is the player able to differentiate between livestreams and VOD assets? The error message "Stream is Offline" only applies to livestreams, so we'd want the error message to be different if we're unable to give a different experience between live and VOD.

**Comment by 0xcadams** [comment]
Yes, we get a response including `"live" | "vod" | "recording"` from the backend, so we can distinguish

**Comment by adamsoffer** [comment]
Here are the "Offline" and "Private" view designs by Vadym.

https://www.figma.com/file/dgNNV2zARuwL0hizYqdJxl/UI?node-id=410%3A234&t=pUf3uCp9Gpfnw9t9-1
