### ISSUE TITLE
Research whether adding additional playback protocols other than HLS + LLHLS is worth the effort

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/ui-kit#18]

**Comment by pglowacky** [comment]
Head's up that I'm currently working with @ArcAster to understand performance of these additional protocols to make this choice.

**Comment by 0xcadams** [comment]
Is this driven more by the Studio provider than the SDK? We may want to close this until upstream supports other protocols

**Comment by 0xcadams** [comment]
Going to close this until upstream adds more protocols and we have choices
