### ISSUE TITLE
[bug] RN player gets stuck in play state

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest prerelease

### Current Behavior

Exiting the RN player fullscreen causes it to get stuck in a play state even though it's paused

**Comment by 0xcadams** [comment]
https://user-images.githubusercontent.com/32714304/207917441-034c7315-286c-45a3-a350-04a22512b09b.mov


https://user-images.githubusercontent.com/32714304/207917979-046a5438-b4b6-43a6-92f6-3ffe79d3e467.mov

**Comment by 0xcadams** [comment]
Filed a bug upstream: https://github.com/expo/expo/issues/20563

**Comment by pglowacky** [comment]
@0xcadams Does this happen 100% of the time or only sometimes? Curious if you think this should block launch.

**Comment by 0xcadams** [comment]
Yeah, it's 100% of the time and blocks launch!

**Comment by 0xcadams** [comment]
Okay so after further investigation, this only happens on the simulator and it happens on all video players, including non-expo ones. 

https://github.com/react-native-video/react-native-video/issues/479
https://github.com/expo/expo/issues/1491

Closing
