### ISSUE TITLE
[bug] Livepeer theme not being applied on NextJs without dynamic import

### ISSUE THREAD

**Issue by sasicodes** [livepeer/ui-kit#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-next.13

### Current Behavior

Weird but happening 🙇🏻 Without dynamic import lazy load/ssr: false the video player theme is set to default (green one). With the below import lazy load, it works fine!

```
const VideoPlayer = dynamic(() => import('web-ui/VideoPlayer'), {
  ssr: false
})
```

### Expected Behavior

Styles should work with normal import.

**Comment by 0xcadams** [comment]
Docs fixes made here:
https://github.com/livepeer/docs/pull/279/files#diff-457ff3b8f7e47d7d6b5fc1c9996fe162b3f63e159a4f9b3fa25d9ee7afb49ebb
