### ISSUE TITLE
Add viewership capabilities in the SDK

### ISSUE THREAD

**Issue by victorges** [livepeer/ui-kit#21]
Both 
 - Some client/provider that can fetch viewership info for an asset as
 - Support in the player for displaying viewership data

**Comment by pglowacky** [comment]
No longer blocked -- viewership API MVP is complete

**Comment by 0xcadams** [comment]
This is still blocked by upstream work

**Comment by victorges** [comment]
@0xcadams I believe this can be developed on the API under `livepeer.monster/data/views/<playbackId>/total`

The only thing that is going to change is adding the `/api` prefix to that path.

Is there anything blocking development on top of that API right now?

**Comment by 0xcadams** [comment]
I will develop against that API, we just won't be able to release until that's released to production

**Comment by victorges** [comment]
Agreed
