### ISSUE TITLE
[bug] Lot of API requests when video is not even playing

### ISSUE THREAD

**Issue by sasicodes** [livepeer/ui-kit#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-next.13

### Current Behavior

When many players were rendered on the list on a screen, there are a lot of API calls. 😞 

https://www.veed.io/view/ceb3ecfc-ee52-4797-a8a7-503ce7ed81be?panel=share

### Expected Behavior

We can fetch and auto-upload things when there is user interaction like `play` in the player.

**Comment by sasicodes** [comment]
cc @0xcadams

**Comment by 0xcadams** [comment]
This should be fixed by https://github.com/livepeer/livepeer.js/issues/60
