### ISSUE TITLE
[bug] Video restarts when transcoding completed

### ISSUE THREAD

**Issue by sasicodes** [livepeer/ui-kit#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

next.13

### Current Behavior

If I am watching a video for first time and im in the middle of the video, suddenly it restarts.

Might be because the transcoding of the video completed with HLS url, the player resets the current source to play the stream.

### Expected Behavior

It is good to play with the stream but may be from the currentTime!?

**Comment by pglowacky** [comment]
@0xcadams is this the same as #230? https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/gh/livepeer/livepeer.js/230

**Comment by 0xcadams** [comment]
@pglowacky It's not, it's similar though. This is for when the upload is successful and the video starts playback from the newly uploaded source. The linked issue #230 is for when the upload isn't successful but continuously loops while attempting to upload the large file. We'll likely want to fix both at the same time, though.

**Comment by 0xcadams** [comment]
This should be fixed with https://github.com/livepeer/livepeer-react/pull/459
