### ISSUE TITLE
[bug] very large arweave files cause upload loop with auto upload

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

Arweave is failing to respond 95% of the time, and the browser is continually trying to play back from Arweave directly. When it does succeed, it only serves a very small portion and then fails, which resets the upload.

### Expected Behavior

It should not reset the upload when playback starts and stops.

### Steps To Reproduce

ar://fdfso9ozftj3gygbspntyrormdkuljrhfqhhr9toonc

**Comment by ericxtang** [comment]
Noting that <https://arweave.net/FdFsO9oZfTj3GYgbSpNTyroRmdKulJRHFQHhr9TooNc> plays ok in the browser.  So would be good to understand why Arweave is failing to respond 95% of the time when the player is doing `fallback` video playback.
