### ISSUE TITLE
[bug] error - TypeError: create__default.default is not a function

### ISSUE THREAD

**Issue by KodeSage** [livepeer/ui-kit#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.1.0

### Current Behavior

When installed on nextjs application, and run  `npm run dev`, it flags the above error

I had to delete my node modules and .next folders , installed it again and when you start the server, it still flags the error

### Expected Behavior

To work properly

**Comment by KodeSage** [comment]
@dob @iameli @ericxtang

**Comment by Shih-Yu** [comment]
See Discord for reponse to this question:
https://discord.com/channels/423160867534929930/426114749370204170/1065347166173937795
