### ISSUE TITLE
Multiple assets uploaded for a single video

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/ui-kit#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.1.0

### Current Behavior

Multiple assets get created for a single video using `autoUrlUpload` in Player
https://discord.com/channels/423160867534929930/983109869869617213/1066292153929715742

first - 604e7c2f-3b99-4f4b-9b88-6fbae8b10ce7
latest - b5cf0dad-b85f-4c3d-9470-fa0cdeb956e3
![](https://cdn.discordapp.com/attachments/983109869869617213/1066292153732575272/image.png)

### Expected Behavior

Only one asset should be created for each upload

**Comment by 0xcadams** [comment]
This is pretty difficult to reproduce - we will have to put this back into the backlog and continue to monitor. This is only possible if the playbackInfo endpoint does not respond for a CID which has been uploaded, so this is likely a Studio issue, but should remain in this repo.

**Comment by 0xcadams** [comment]
This should be fixed with https://github.com/livepeer/livepeer-react/pull/459
