### ISSUE TITLE
[bug] Can't package with parcel because of "process" being undefined

### ISSUE THREAD

**Issue by iameli** [livepeer/ui-kit#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.5.8

### Current Behavior

I've got a pretty simple app here, it looks like this 

```tsx
import React from "react";
import ReactDOM from "react-dom";
import { Player } from "@livepeer/react";

const div = document.createElement("div");
div.innerHTML = "hello";
div.id = "iameli-streams";
document.body.prepend(div);

const App = () => {
  return (
    <div>
      <Player playbackId="bb046er0yawh006o"></Player>
    </div>
  );
};

ReactDOM.render(<App />, document.querySelector("#iameli-streams"));
```

I'm attempting to build it with Parcel, with this configuration
```json
{
  "name": "iameli-streams",
  "version": "1.0.0",
  "browser": "dist/iameli-streams.js",
  "license": "MIT",
  "dependencies": {
    "@livepeer/react": "^2.5.8",
    "nodemon": "^2.0.22",
    "npm-run-all": "^4.1.5",
    "parcel": "^2.9.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "scripts": {
    "dev": "run-p dev:rebuild dev:ngrok",
    "dev:rebuild": "nodemon -w src/ -e tsx -x yarn run prepare",
    "dev:ngrok": "ngrok http file://$(realpath dist) --log=stderr --log-format=logfmt --host-header=rewrite",
    "prepare": "parcel build --target browser ./src/index.tsx --dist-dir dist"
  },
  "targets": {
    "main": false,
    "browser": {
      "context": "browser",
      "includeNodeModules": true,
      "outputFormat": "esmodule"
    }
  },
  "browserslist": "> 0.5%"
}
```

This builds just fine, but results in an error when executing on this line:
```
var $3sXIf$process = require("process");
```
Which yields:
```
iameli-streams.js?cache=1688335387859:1 Uncaught ReferenceError: require is not defined
    at iameli-streams.js?cache=1688335387859:1:22
```

My environment doesn't know what `require` or `process` are, I think. Is there maybe somewhere in the library where we're assuming Webpack/Next's conventions around that variable existing...?

I've successfully worked around the issue by adding an empty `process` field and aliasing it, so that's...

`src/process.tsx`:
```tsx
export default {
  env: {},
};
```

And then this in package.json:
```
  "alias": {
    "process": "./src/process.tsx"
  }
```

But it'd be nice not to need that workaround; I think we just need to be conditional in places where we include `process.env` and not always assume it exists?

**Comment by 0xcadams** [comment]
I think this a downstream issue with parcel, and unrelated to livepeer.js. Webpack or Browserify should help with this.

**Comment by 0xcadams** [comment]
This should be fixed with https://github.com/livepeer/livepeer-react/pull/459
