### ISSUE TITLE
[bug] <Player> requires a StudoProvider for unclear reasons

### ISSUE THREAD

**Issue by iameli** [livepeer/ui-kit#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.5.8

### Current Behavior

I've got a stream running at `bb046er0yawh006o`. I can view that stream on https://lvpr.tv/?v=bb046er0yawh006o. Hooray!

I'd expect that the `<Player>` component would function exactly the same way, if I just use: 
```jsx
<Player playbackId="bb046er0yawh006o"></Player>
```
But that doesn't work; it complains about the lack of a provider. An empty API key works, though, indicating there doesn't need to be _much_ of a provider:
```jsx
const livepeerClient = createReactClient({
  provider: studioProvider({ apiKey: "" }),
});

const App = () => {
  return (
    <div>
      <LivepeerConfig client={livepeerClient}>
        <Player playbackId="bb046er0yawh006o"></Player>
      </LivepeerConfig>
    </div>
  );
};

ReactDOM.render(<App />, document.querySelector("#iameli-streams"));

```

**Comment by 0xcadams** [comment]
Is this a bug? We will eventually require API keys on all endpoints

**Comment by 0xcadams** [comment]
closing as non-issue
