### ISSUE TITLE
Fix tus in Studio provider to use the correct fingerprint

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#37]
tus uploads do not resume correctly for the Studio provider, since the [fingerprint](https://github.com/tus/tus-js-client/blob/6f723f07b016cd374d4fe65140a2794e8ca7ca56/lib/browser/fileSignature.js) for files includes the tus endpoint, which changes on each upload (when we make a request to `/asset/request-upload`). This should be fixed to not include the endpoint in the fingerprint.

This is in the studio provider createAsset function, where in the Tus upload, there is an option to override the file fingerprint to a custom function. We should override this to include every file parameter except for the upload url.

https://github.com/tus/tus-js-client/blob/6f723f07b016cd374d4fe65140a2794e8ca7ca56/docs/api.md#fingerprint

**Comment by 0xcadams** [comment]
@suhailkakar is taking this, waiting on access to Github to assign

**Comment by suhailkakar** [comment]
fixed: #112

**Comment by suhailkakar** [comment]
@0xcadams I think we can close this issue, as it is already completed. #122

**Comment by 0xcadams** [comment]
Yep, done!

**Comment by 0xcadams** [comment]
This is a bug again with the most recent revert to fix issues with resumable uploads: https://github.com/livepeer/livepeer.js/pull/158/files

Context here:
https://discord.com/channels/423160867534929930/1009165020837466203/1044353649163382844
