### ISSUE TITLE
[bug] Type missmatch

### ISSUE THREAD

**Issue by pblvrt** [livepeer/ui-kit#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

3.1.9

### Current Behavior

`Property 'playbackId' does not exist on type 'StreamSession'` when using `useStreamSessions` hook

The api does return a playbackId for streamSession

**Comment by 0xcadams** [comment]
This should be fixed with https://github.com/livepeer/livepeer-react/pull/459
