### ISSUE TITLE
[LJS-1] Add Settings Popover (Playback Speed & Quality)

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#53]
<img width="369" alt="Screen Shot 2022-09-23 at 9 42 26 AM" src="https://user-images.githubusercontent.com/32714304/192010706-74a5757a-3537-4a62-a193-8f56d5c1c371.png">

<sub>[LJS-1](https://linear.app/livepeer/issue/LJS-1/add-settings-popover-playback-speed-and-quality)</sub>

**Comment by pglowacky** [comment]
Heard from Bonfire that they're very interested in the playback speed work because their users are using Livepeer for audio-only use cases and this is a common feature

**Comment by pglowacky** [comment]
Heard from Bonfire that they're very interested in the playback speed work because their users are using Livepeer for audio-only use cases and this is a common feature

**Comment by sasicodes** [comment]
+1

**Comment by 0xcadams** [comment]
This should be relatively straightforward, we will need designs first (cc @vadymdrut @adamsoffer) and the implementation should be a couple days with expo-av [1] and hls.js [2]

[1] https://docs.expo.dev/versions/latest/sdk/video/#rate
[2] https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

**Comment by adamsoffer** [comment]
@0xcadams design for both playback speed and quality can be found [here](https://www.figma.com/file/dgNNV2zARuwL0hizYqdJxl/UI?node-id=410%3A2&t=fyf0OjTC2RKrYErN-1)

**Comment by 0xcadams** [comment]
> @0xcadams design for both playback speed and quality can be found [here](https://www.figma.com/file/dgNNV2zARuwL0hizYqdJxl/UI?node-id=410%3A2&t=fyf0OjTC2RKrYErN-1)

Perfect, thanks!
