### ISSUE TITLE
NFT Minting SDK (Aptos)

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#58]

**Comment by pglowacky** [comment]
High level requirements: 


- Should allow users to upload MP4 and MOV files
- Should allow users to decide on which chain they’d like to mint their NFTs (Aptos or Polygon)
- Should store asset and metadata on IPFS and return a URI and CID, respectively
    - We should not store the metadata directly on chain (Aptos allows this as a possibility)
- Should provide documentation on how to properly set the metadata for Aptos and ERC-721, to be compatible with EVM chains
    - Metadata should point to the CID, rather than an embeddable player.
- Livepeer Player should allow users to playback directly from a CID
- Documentation should include how to use the Livepeer Player to play directly back from a CID.
- Should provide documentation on how to mint using either `createToken` SDK (Aptos) or wagmi/ethers
- Should include a sample application (requirements below)

https://miro.com/app/board/uXjVPVNAgsQ=/
