### ISSUE TITLE
Export Player React Component inside Livepeer.js

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/ui-kit#8]
## Story
As a user I want to be able to export a `Player` component from the `@livepeer/react` package so that I can stream videos using livepeer.js without having to install third party dependencies. Example: `import { Player } from "@livepeer/react";`

## Task
- [ ] Move the [`VideoPlayer`](https://github.com/livepeer/livepeer.js/blob/main/docs/components/core/VideoPlayer.tsx) component out of the `docs` app and into `react` package.

**Comment by adamsoffer** [comment]
Hey @clacladev I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by clacladev** [comment]
On it

**Comment by 0xcadams** [comment]
Completed with https://github.com/livepeer/livepeer.js/pull/26
