### ISSUE TITLE
Add example starter to next.js open examples

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/ui-kit#83]
`with-livepeer` example, to be created by `npx create-next-app --example with-livepeer with-livepeer-app`

https://github.com/vercel/next.js/tree/canary/examples

**Comment by pratham-bhatnagar** [comment]
Hey @0xcadams , I want to contribute on this

**Comment by pratham-bhatnagar** [comment]
https://github.com/livepeer/livepeer.js/tree/main/examples/next 
Can I take this example code as a reference

**Comment by 0xcadams** [comment]
Hey @pratham-bhatnagar, that would be great! Yeah, that would be a good place to start. Feel free to add any features you'd like - it will need to be maintained over time, so let us know if you're interested in taking that responsibility. If not, let's plan to keep the feature set small so that there aren't many updates required

**Comment by pratham-bhatnagar** [comment]
Yeah, I would love to take the responsibility to maintain this part of the project.

**Comment by pratham-bhatnagar** [comment]
https://github.com/livepeer/livepeer.js/tree/main/examples/next
This example code is to added to next.js repo right?

**Comment by 0xcadams** [comment]
Sounds great! Thanks for that. And yes, that example would be great. If you also could add a bit more comments/documentation to the README, that would be awesome (since that audience are not all familiar with Livepeer/web3).

**Comment by 0xcadams** [comment]
Were you able to make any progress on this? @pratham-bhatnagar
