### ISSUE TITLE
Make sure viewership plugin can be used without the Livepeer Player

### ISSUE THREAD

**Issue by victorges** [livepeer/ui-kit#99]
This could mean only documentation, but maybe some improvements
will be necessary on the plugin logic so it's easier to use (ideally 1 function call).

**Comment by victorges** [comment]
@0xcadams how much work do you think this would be?

**Comment by 0xcadams** [comment]
It would be a couple hours, I think documentation and very minor refactor. Just weird thing to document currently, since we don't have the plain JS docs (which I think should be high priority)

**Comment by victorges** [comment]
New ctx: None of our users are using our player yet, and we should provide a viewership solution for them without needing to switch completely to our player.

**Comment by 0xcadams** [comment]
https://github.com/livepeer/livepeer.js/blob/main/examples/svelte/src/lib/Video.svelte#L39-L42

Do we need anything outside of this?

**Comment by victorges** [comment]
@0xcadams In my opinion yes, since that interface exposes what would be just an implementation detail of our solution with the reporting URL and all of the HLS native support logic (which seems like should be independent of metrics reporting?).

The state of art to me would be [something like mux's](https://docs.mux.com/guides/data/monitor-html5-video-element), where you call 1 function passing your video element (or an identifier to find it), and it will configure everything as necessary. This also seems relatively straightforward to implement on our side, as it would be just a function that abstracts those impl details?

Adapting mux's example, I was hoping we could just tell developers to do something like this:
```ts
import { setupPlayerMetrics } from 'livepeer';

// Initialize Livepeer viewership metrics by passing in the "id" attribute of your video player
setupPlayerMetrics('#my-player').then(success => { // this could be a regular thrown error caught with `catch()` as well, tho that'd be less friendly with `await`
  if (!success) {
    console.error('Not able to report player metrics');
  }
})
```
(or similarly to mux, on react with a ref and passing the ref to the func)

Also, it might be necessary to have that `setupPlayerMetrics` also configure some kind of callback when the video element state changes? 
e.g. it might be called when there's no `src` configured, but if it changes we want to update the reporting URL as well so we should be aware of those. Ideally we should not let that complexity on user's hands as well. For an MVP it seems ok to just document "you must only do this after setting your player src" tho.

WDYT?

**Comment by 0xcadams** [comment]
> @0xcadams In my opinion yes, since that interface exposes what would be just an implementation detail of our solution with the reporting URL and all of the HLS native support logic (which seems like should be independent of metrics reporting?).
> 
> The state of art to me would be [something like mux's](https://docs.mux.com/guides/data/monitor-html5-video-element), where you call 1 function passing your video element (or an identifier to find it), and it will configure everything as necessary. This also seems relatively straightforward to implement on our side, as it would be just a function that abstracts those impl details?
> 
> Adapting mux's example, I was hoping we could just tell developers to do something like this:
> 
> ```ts
> import { setupPlayerMetrics } from 'livepeer';
> 
> // Initialize Livepeer viewership metrics by passing in the "id" attribute of your video player
> setupPlayerMetrics('#my-player').then(success => { // this could be a regular thrown error caught with `catch()` as well, tho that'd be less friendly with `await`
>   if (!success) {
>     console.error('Not able to report player metrics');
>   }
> })
> ```
> 
> (or similarly to mux, on react with a ref and passing the ref to the func)
> 
> Also, it might be necessary to have that `setupPlayerMetrics` also configure some kind of callback when the video element state changes? e.g. it might be called when there's no `src` configured, but if it changes we want to update the reporting URL as well so we should be aware of those. Ideally we should not let that complexity on user's hands as well. For an MVP it seems ok to just document "you must only do this after setting your player src" tho.
> 
> WDYT?

Okay we can change to one-line, however the error handling case is exactly the same as above, so I'm not sure what we're fixing here (it'll just throw if there's no metrics reporting url for that src?).

And I don't think we need to handle the src changing, that should be handled by the client in something like useEffect, not by the reporting code. It wouldn't make sense for it to be handled downstream.

**Comment by 0xcadams** [comment]
```tsx
const metricReportingUrl = await getMetricsReportingUrl(src);
if (metricReportingUrl) {
  reportMediaMetrics(video, metricReportingUrl);
} else {
  console.log(
    'Not able to report player metrics given the source url',
    source,
  );
}
```

This is the current API. I think that's pretty succint.

**Comment by 0xcadams** [comment]
Are people asking for this? Why aren't they being referred to migrating to our Player for much easier integrations and more features?

**Comment by victorges** [comment]
> Okay we can change to one-line, however the error handling case is exactly the same as above, so I'm not sure what we're fixing here (it'll just throw if there's no metrics reporting url for that src?).

On the version I suggested there's no throw, so users would be able to call it and ignore the result, but `await`/`then` for it if they care if the reporting was successful or not. 

> And I don't think we need to handle the src changing, that should be handled by the client in something like useEffect, not by the reporting code. It wouldn't make sense for it to be handled downstream.

I see, sure, you know better. I think the minimum here then would be a way to stop an existing metrics reporting (which would be done in case the video src changes). Is there a way to do that?

> This is the current API. I think that's pretty succint.

IMO the metrics reporting URL is an implementation detail which we might want to change in the future, but more than that, it's an abstraction that users do not need to be aware of. So I think it makes it more confusing for the users as they should not care about what a reporting URL is to have to fetch and pass it around. 

> anecdote: It's just like that stream health API story, where we previously required the livestream region to be passed in the API. Then to know the health of a stream, first you needed to call some other API to get the region and then call the stream health API. The region here is an implementation detail that users should not be aware of, so even having to handle it is a problem IMO. That would be similar to the reporting URL (which still feels like hack to me, hope we can get rid of it eventually), with the exception that it's also much easier to abstract than on the stream health case.

So I think it would be preferable to abstract that in a 1-line helper, as it'd also be pretty low-effort, and then also have much more freedom to change how this setup happens without needing to break compatibility for the SDK users. I'm also OK if you prefer to send a separate `src` argument to the setup func additionally from the `video` element, but if there are no downsides we could also fetch it from `video.src` and have only 1 arg (sending the `src` might be good since we won't be auto-detecting `src` changes, so it becomes an explicit dependency, easier to track for example on react).

Also, the snippet you sent is not the whole code on the Svelte example. Would the other stuff not be necessary for external players? e.g. If a user is using their own hls.js, could they just plug the `reportMediaMetrics` after setting it up or would they need some special/different logic which is done in that `createNewHls`?

**Comment by pglowacky** [comment]
> Are people asking for this? Why aren't they being referred to migrating to our Player for much easier integrations and more features?

Yes, people are asking for it. We have a few projects (Beem and SubbSpace, in particular) that have indicated that they're not interested in changing their player in the short term but want to get viewership metrics. Beem has told me specifically that the integration with their player is relatively complex, so they'd absolutely like to avoid changing it out if possible. 

Additionally, we're going to be using the flawless playback metric here as a key QoS metric to be proactive about reliability and this metric is only useful if we get as many possible users using the plug-in or player. Right now, the flawless playback metric for VOD is still pretty useless because we don't have enough users using the player today.
